# This GitHub action updates the Chromatic build everytime the `fractal-react`
# package is updated.

name: Fractal/React

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Deploying Fractal/React Storybook to Chromatic
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files from Design Tokens, Fractal and React UI library
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: |
            packages/design-tokens/**
            packages/react/**
            apps/fractal/**

      - if: steps.changed-files-specific.outputs.any_changed != 'true'
        name: No need to update Chromatic for Fractal/React
        run: |
          echo "There are no changes in Design Tokens, Fractal or React UI library."
          echo "SKIP_CHROMATIC=1" >> $GITHUB_ENV

      - if: env.SKIP_CHROMATIC != 1
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - if: env.SKIP_CHROMATIC != 1
        name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - if: env.SKIP_CHROMATIC != 1
        name: Starting TurboRepo local cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - if: env.SKIP_CHROMATIC != 1
        name: Setting up Git to access Freezer
        env:
          FREEZER_TOKEN: ${{ secrets.FREEZER_TOKEN }}
        run: ./scripts/setup-freezer.sh

      - if: env.SKIP_CHROMATIC != 1 && github.event_name == 'push'
        name: Waiting for security to pass
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: Checking Yarn cache's integrity
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - if: env.SKIP_CHROMATIC != 1 && github.event_name == 'push'
        name: Waiting for quality to pass
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: Checking code quality
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - if: env.SKIP_CHROMATIC != 1 && github.event_name == 'push'
        name: Building and publishing to Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_REACT_PROJECT_TOKEN }}
        run: |
          yarn workspace @snowball-tech/fractal-react build:chromatic --exit-zero-on-changes --exit-once-uploaded --no-interactive

      - if: env.SKIP_CHROMATIC != 1 && github.event_name == 'pull_request'
        name: Building and publishing to Chromatic with Snapshot testing
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_REACT_PROJECT_TOKEN }}
        run: |
          yarn workspace @snowball-tech/fractal-react build:chromatic
          --no-interactive

      - if: env.SKIP_CHROMATIC != 1
        uses: actions/upload-artifact@v3
        with:
          name: Storybook build log
          path: ./packages/react/build-storybook.log
