# This GitHub action updates the Chromatic build everytime the `fractal-react`
# package is updated.

name: React UI Library - Chromatic

on:
  push:
    branches:
      - main
    paths:
      - 'apps/fractal/**'
      - 'packages/react/**'

jobs:
  chromatic-deployment:
    name: Deploying React UI Library Storybook to Chromatic
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - name: Starting TurboRepo local cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Publish to Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_REACT_PROJECT_TOKEN }}
        run: yarn workspace @snowball-tech/fractal-react build:chromatic --exit-zero-on-changes
